/**
 * Role-Permission Mapping
 * Maps each user role to their allowed permissions
 */

import { UserRole } from "@prisma/client";
import { Permission, PERMISSIONS } from "./definitions";

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  /**
   * CLIENT Role
   * Regular users who can manage their own forms and data
   */
  CLIENT: [
    // Forms - Own only
    PERMISSIONS.FORM_CREATE,
    PERMISSIONS.FORM_READ_OWN,
    PERMISSIONS.FORM_UPDATE_OWN,
    PERMISSIONS.FORM_DELETE_OWN,
    PERMISSIONS.FORM_PUBLISH_OWN,

    // Submissions - Own forms only
    PERMISSIONS.SUBMISSION_READ_OWN,
    PERMISSIONS.SUBMISSION_EXPORT_OWN,
    PERMISSIONS.SUBMISSION_DELETE_OWN,

    // Analytics - Own forms only
    PERMISSIONS.ANALYTICS_READ_OWN,
    PERMISSIONS.ANALYTICS_EXPORT_OWN,

    // User - Own profile only
    PERMISSIONS.USER_UPDATE_OWN,
    PERMISSIONS.USER_DELETE_OWN,
  ],

  /**
   * ADMIN Role
   * Superusers with full platform access
   */
  ADMIN: [
    // Forms - All operations, all users
    PERMISSIONS.FORM_CREATE,
    PERMISSIONS.FORM_READ_OWN,
    PERMISSIONS.FORM_READ_ALL,
    PERMISSIONS.FORM_UPDATE_OWN,
    PERMISSIONS.FORM_UPDATE_ALL,
    PERMISSIONS.FORM_DELETE_OWN,
    PERMISSIONS.FORM_DELETE_ALL,
    PERMISSIONS.FORM_PUBLISH_OWN,
    PERMISSIONS.FORM_PUBLISH_ALL,

    // Submissions - All operations, all forms
    PERMISSIONS.SUBMISSION_READ_OWN,
    PERMISSIONS.SUBMISSION_READ_ALL,
    PERMISSIONS.SUBMISSION_EXPORT_OWN,
    PERMISSIONS.SUBMISSION_EXPORT_ALL,
    PERMISSIONS.SUBMISSION_DELETE_OWN,
    PERMISSIONS.SUBMISSION_DELETE_ALL,

    // Analytics - Platform-wide access
    PERMISSIONS.ANALYTICS_READ_OWN,
    PERMISSIONS.ANALYTICS_READ_ALL,
    PERMISSIONS.ANALYTICS_READ_PLATFORM,
    PERMISSIONS.ANALYTICS_EXPORT_OWN,
    PERMISSIONS.ANALYTICS_EXPORT_ALL,

    // User Management - Full control
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_READ_DETAILS,
    PERMISSIONS.USER_UPDATE_OWN,
    PERMISSIONS.USER_UPDATE_ALL,
    PERMISSIONS.USER_DELETE_OWN,
    PERMISSIONS.USER_DELETE_ALL,
    PERMISSIONS.USER_CHANGE_ROLE,
    PERMISSIONS.USER_IMPERSONATE,
    PERMISSIONS.USER_VIEW_ACTIVITY,

    // System - Full access
    PERMISSIONS.SYSTEM_ACCESS_ADMIN,
    PERMISSIONS.SYSTEM_VIEW_LOGS,
    PERMISSIONS.SYSTEM_VIEW_METRICS,
    PERMISSIONS.SYSTEM_CONFIGURE,
    PERMISSIONS.SYSTEM_MANAGE_INTEGRATIONS,
  ],
};
